"""make payment method nullable

Revision ID: df8182ce333d
Revises: d4544e1efa5c
Create Date: 2026-02-13 19:26:01.896298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8182ce333d'
down_revision: Union[str, Sequence[str], None] = 'd4544e1efa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_method',
               existing_type=postgresql.ENUM('blik', 'card', 'transfer', name='paymentmethod'),
               nullable=True)
    op.alter_column('shipment', 'tracking_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'tracking_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payment', 'payment_method',
               existing_type=postgresql.ENUM('blik', 'card', 'transfer', name='paymentmethod'),
               nullable=False)
    # ### end Alembic commands ###
