"""few parameters fix

Revision ID: 691673677fb1
Revises: df8182ce333d
Create Date: 2026-02-14 23:00:44.973362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '691673677fb1'
down_revision: Union[str, Sequence[str], None] = 'df8182ce333d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('order', sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('shipment', sa.Column('shipping_email', sa.String(), nullable=False))
    op.add_column('shipment', sa.Column('shipping_company', sa.String(), nullable=True))
    op.add_column('shipment', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('shipment', sa.Column('nip', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'shipment', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='unique')
    op.drop_column('shipment', 'nip')
    op.drop_column('shipment', 'comment')
    op.drop_column('shipment', 'shipping_company')
    op.drop_column('shipment', 'shipping_email')
    op.drop_column('order', 'shipping_cost')
    op.drop_column('order', 'updated_at')
    # ### end Alembic commands ###
