"""discounts

Revision ID: edb4578a2df7
Revises: 691673677fb1
Create Date: 2026-02-15 17:31:54.593135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb4578a2df7'
down_revision: Union[str, Sequence[str], None] = '691673677fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('contact_email', sa.String(), nullable=True))
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_item', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('product', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'views')
    op.alter_column('order_item', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order', 'contact_email')
    # ### end Alembic commands ###
